name: Serverless Python Tests

on:
  push:
    paths:
      - "serverless/**"
  pull_request:
    paths:
      - "serverless/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: serverless

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        run: python -m unittest discover -s ./ -p '*_test.py'
